all: rgba-1.12.gif rgba-1.8.gif

gen_color_map: gen_color_map.c
	gcc -g -Wall `pkg-config --cflags --libs ImageMagick-7.Q16HDRI` gen_color_map.c -o gen_color_map

rgba-1.12.gif: rgba-1.12.txt gen_color_map
	./gen_color_map rgba-1.12.txt rgba-1.12.gif

rgba-1.8.gif: rgba-1.8.txt gen_color_map
	./gen_color_map rgba-1.8.txt rgba-1.8.gif

clean:
	rm gen_color_map rgba-*.gif

.PHONY: clean all
