name: 'CI'

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.ccache
            ~/.vcpkg
          key: ${{ runner.os }}-win-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-win-
      - run: ./.ci/linux-mingw.sh
        name: 'Build Windows binaries'
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: mingw
          path: package/
